### PR TITLE
ServiceX configuration on Jetstream

### PR DESCRIPTION
**Pull request by zonca**
See https://github.com/pondd-project/pondd/issues/6

## Urls

* https://pondd-minio.zonca.dev/
* https://pondd-servicex.zonca.dev/

### CODE REVIEW

**Review by BenGalewsky — APPROVED** [review]
The changes make sense. Welcome to ServiceX!

**Comment by zonca** [comment]
## Warnings in helm

```
W0929 17:22:04.435327   17991 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v
1 Ingress
W0929 17:22:04.491185   17991 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingre
ss
W0929 17:22:05.383446   17991 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingre
ss
W0929 17:22:05.386995   17991 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v
1 Ingress
```

**Comment by zonca** [comment]
## Postgres pod

```
  Warning  FailedScheduling  2m29s  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  2m29s  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims. 
  Warning  FailedScheduling  2m5s   default-scheduler  0/2 nodes are available: 2 node(s) didn't match node selector.
```

**Comment by zonca** [comment]
@BenGalewsky, @gordonwatts see errors above, do I need specific selectors? and can I specify a storageclass somewhere?

**Comment by zonca** [comment]
> @BenGalewsky, @gordonwatts see errors above, do I need specific selectors? and can I specify a storageclass somewhere?

actually I have already set the storageclass, I don't understand that error (`2 pod has unbound immediate PersistentVolumeClaims.`)

## PVC

```
data-servicex-postgresql-0   Bound    pvc-be8ce862-9cdc-4b52-895e-7c741c2ebfcb   8Gi        RWO            standard       22m
data-servicex-rabbitmq-0     Bound    pvc-70e6218d-8a91-4eb7-9f3f-33a1101f4ad7   8Gi        RWO            standard       22m
```

**Comment by BenGalewsky** [comment]
Well, this is just the standard [Bitnami Postgres Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) - it may be some configuration problem with your cluster, but it's hard to tell from here. 

For development it's fine (and maybe preferable) to turn off persistence for RabbitMQ and Postgres. The chart will just use an `EmptyDir` volume which goes away when the pod restarts, but that's not a big deal for development. Especially true with authentication to ServiceX turned off so there aren't even users to keep track of.

```yaml
postgresql:
  persistence:
    enabled: false
rabbitmq:
    persistence:
      enabled: false
minio:
  persistence:
    enabled: false
```

**Comment by zonca** [comment]
thanks @BenGalewsky , the Bitnami postgres works fine on the cluster. Investigating more.

**Comment by zonca** [comment]
@BenGalewsky oh it was just the `kernel-ml=true` node selector. Now the deployment seems to work. Do I need to apply that label to all my nodes? can you make that optional or configurable in the chart?

**Comment by BenGalewsky** [comment]
> @BenGalewsky oh it was just the `kernel-ml=true` node selector. Do I need to apply that label to all my nodes? can you make that optional or configurable in the chart?

I don't see where that comes from. What is using that selector?

**Comment by zonca** [comment]
> > @BenGalewsky oh it was just the `kernel-ml=true` node selector. Do I need to apply that label to all my nodes? can you make that optional or configurable in the chart?
> 
> I don't see where that comes from. What is using that selector?

the postgres pod `Node-Selectors:  kernel-ml=true`

**Comment by BenGalewsky** [comment]
Please remove that from `values.yaml` - it must be a University of Chicago-ism that is certainly not universal

**Comment by zonca** [comment]
didn't notice it was in `values.yaml`, thanks!

**Pull request merged**
